package entity;
//Список команд передаваемых в сообщениях для общения сервера и клиента
public enum Command {
    CHANNEL_HAS_BEEN_ACTIVATED,
    DOWNLOADING_FROM_SERVER,
    DOWNLOADING_FROM_CLIENT,
    AUTHORIZATION_CONFIRMED,
    CLIENT_DISCONNECT,
    REGISTRATION_NEW_CLIENT,
    REGISTRATION_CONFIRMED,
    USER_NOT_FOUND_IN_DATABASE,
    CREATE_DIRECTORY;
}
